# hydra config
hydra:
  run:
    dir: ${train.log_path}
  job:
    chdir: false
  sweep:
    dir: logs/phasemix/
    subdir: ${train.experiment}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    params:
      filter.phase: mix, stance, swing, whole

optimizer:
  lr: 0.0001
  beta1: 0.5
  beta2: 0.999

data:
  root_path: /workspace/data # dataset path

  seg_data_path: ${data.root_path}/segmentation_dataset_512/ # segmentation dataset path
  gait_seg_data_path: ${data.root_path}/segmentation_dataset_512/json_mix_with_score/${filter.phase} # defined gait cycle json path. This path uesd be gait cycle defined dataset.
  gait_seg_index_data_path: ${data.root_path}/filter_dataset/index_mapping # training mapping path, this used for cross validation, with different class number.

  num_workers: 8
  img_size: 224
  sampling: "over" # over, under, none

  gait_cycle_batch_size: 1 # this used for gait cycle defined method.
  default_batch_size: 1 # this used for default method, without gait cycle defined method.

model:
  model: ${train.backbone} # the model name
  model_class_num: 3 # the class num of model. 2 > [ASD, non_ASD]. 3 > [ASD, DHS, LCS_HipOA]. 4 > [ASD, DHS, LCS_HipOA, normal]
  model_depth: 50 # choices=[50, 101, 152], help='the depth of used model'

filter:
  phase: "mix" # stance, swing, mix, whole
  path: ckpt/
  backbone: 2dcnn # choices=[3dcnn, 2dcnn, vit], help='the backbone of the model'

train:
  # Training config
  max_epochs: 50 # numer of epochs of training

  # used for val
  clip_duration: 1 # clip duration for the video
  uniform_temporal_subsample_num: 8 # num frame from the clip duration, f or define one gait cycle, we need use whole frames.

  # experiment: two_stream, cnn_lstm, cnn, 3dcnn
  backbone: 3dcnn # choices=[3dcnn, 2dcnn, cnn_lstm, two_stream], help='the backbone of the model'
  temporal_mix: False # if use the temporal mix
  filter: True # if use the filter method, this will be used for gait cycle defined method.

  experiment: ${train.backbone}_${train.temporal_mix}_${filter.phase}_${filter.backbone} # the experiment name

  gpu_num: 0 # choices=[0, 1], help='the gpu number whicht to train'

  log_path: logs/classifier/${train.experiment}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  fast_dev_run: False # if use the fast_dev_run
  fold: 3 # the fold number of the cross validation
  current_fold: ?? # the current fold number of the cross validation
