# hydra config
hydra:
  run:
    dir: ${train.log_path}
  job:
    chdir: false
    
data:
  seg_data_path: /workspace/data/segmentation_dataset_512/ # segmentation dataset path
  gait_seg_data_path: /workspace/data/segmentation_dataset_512/json_mix # defined gait cycle json path. This path uesd be gait cycle defined dataset. 
  gait_seg_data_path_with_score: /workspace/data/segmentation_dataset_512/json_mix_with_score # defined gait cycle json path. This path uesd be gait cycle defined dataset.

  num_workers: 4
  img_size: 224
  sampling: "over" # over, under, none

model:
  model: 2dcnn # the model name
  model_class_num: 3 # the class num of model. 2 > [ASD, non_ASD]. 3 > [ASD, DHS, LCS_HipOA]. 4 > [ASD, DHS, LCS_HipOA, normal]
  model_depth: 50 # choices=[50, 101, 152], help='the depth of used model'

filter:
  phase: "mix" # stance, swing, mix, whole
  path: ckpt/
  backbone: 2dcnn # choices=[3dcnn, 2dcnn, vit], help='the backbone of the model'

train:
  gpu_num: 0 # choices=[0, 1], help='the gpu number whicht to train'

  log_path: logs/filter_score/${filter.phase}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  fast_dev_run: False # if use the fast_dev_run
  fold: 3 # the fold number of the cross validation
  current_fold: ?? # the current fold number of the cross validation